export enum RoutesName {
    LOGIN_PAGE = "/login",
    UNAUTHORIZED = "/unauthorized",
    REGISTRATION_PAGE = "/registration",
    MAIN_PAGE = "/",
    ANTIVIRUSES_PAGE = "/ant",
    UPDATES_PAGE = "/update",
    ADDITIONAL_PZ = "/additional",
    DOCUMENTS_PAGE = "/documents",
    DEEP_STATE_MAP_PAGE = "/deepstatemap",
    FISHING_PAGE = "/fishing",
    FISHING_CARD_PAGE = "/fishing/card",
    COURSES_PAGE = "/course",
    NEWS_PAGE = "/news",
    CONTACTS_PAGE = "/contacts",
    FAQ = "/faq",
    LAW_BASE = "/law-base",
    SIGNAL = "/signal",
    PROFILE_PAGE = "/profile",
    TEST_RESULT_PAGE = "/test-result",
    ADMIN_PAGE = "/admin",
    ADMIN_NEWS_PAGE="/admin/news",
    ADMIN_ANT_PZ_PAGE="/admin/ant-pz",
    ADMIN_USERS_PAGE="/admin/users",
    ADMIN_UPDATES_PAGE="/admin/updates",
    ADMIN_ADDITIONAL_PZ_PAGE="/admin/additional",
    ADMIN_FISHING_PAGE="/admin/fishing",
    ADMIN_LICENSE_KEYS = "/admin/licenses",
    ADMIN_CREATE_COURSE = "/course/create"

}